name: Build binary

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tinygo-version: ['tinygo:0.39.0', 'tinygo-dev:latest']
        target:
          - xiao-ble
          - nano-33-ble-s140v6-uf2
    container:
      image: ghcr.io/tinygo-org/${{ matrix.tinygo-version }}
      options: --user root
    steps:

    - name: Prepare
      run: |
        apt-get update
        apt-get install -y make

    - name: Work around CVE-2022-24765
      # We're not on a multi-user machine, so this is safe.
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Dependencies
      run: |
        go mod tidy

    - name: Build ${{ matrix.target }} binary
      run: make TARGET=${{ matrix.target }} build

    - name: Store binaries
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ matrix.target }}-tinygo-${{ matrix.tinygo-version }}
        path: build/*
        retention-days: 14
